NAME = sed
CC = c++
CFLAGS = -Wll -Werror -Wextr -std=c++98 -g
SRC = min.cpp
OBJ = $(SRC:.cpp=.o)

ll: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $@

%.o:%.cpp
	$(CC) $(CFLAGS) -c $<


clen:
	rm -rf $(OBJ)

fclen: clen
	rm -rf $(NAME)

re: fclen ll

.Phony: ll clen fclen re 
